name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/michaels-wacky-build.yml
    with:
      solution: FSharpOssTooling.slnx
      fantomas-paths: "src/ tests/"
    permissions:
      contents: read
      checks: write
      pull-requests: write
